### ISSUE TITLE
Horse died and cause exception

### ISSUE THREAD

**Issue by dann1kid** [Ahrondus/VS_Horse#12] opened 2022-02-13 18:03 UTC
```
13.2.2022 21:00:20 [Error] System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Vintagestory.GameContent.EntityBehaviorHarvestable.SetHarvested_Patch2(EntityBehaviorHarvestable this, IPlayer byPlayer, Single dropQuantityMultiplier)
   в Vintagestory.GameContent.ItemKnife.OnHeldInteractStop(Single secondsUsed, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel)
   в Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(_EWaCktsS2JyUbMhFd5RdMtCiCZOA packet, ConnectedClient client)
   в Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket)
   ```

**Comment by G3rste** [comment] 2022-02-13 23:07
Duplicate of [this one](https://github.com/Ahrondus/VS_Horse/issues/10)

**Closed by G3rste** 2022-02-13 23:07 UTC
Labels: duplicate
